project_id = "kyprrtpmvugfcfffaelv"

[functions.youtube-search]
verify_jwt = false

[functions.podcast-search]
verify_jwt = false

[functions.letterboxd-feed]
verify_jwt = false

[functions.sitemap]
verify_jwt = false